### ISSUE TITLE
Implementation of denormalization?

### ISSUE THREAD

**Issue by apsavin** [stevenpetryk/jsonapi-normalizer#10]
Thanks for the lib!

I think, it would be convenient to have a denormalization function in pair with normalization, like in original `normalizr`. What do you think about it?

**Comment by niksy** [comment]
Also looking for this. It could be useful when sending data back to the server.

**Comment by stevenpetryk** [comment]
Hi there! Sorry I missed these, I should probably set up notifications on this repo. It was mostly intended for use in a personal project.

This is definitely something I can imagine would be worth implementing, though I've never worked with an API that _receives_ JSONAPI payloads. I'll look into it when I'm on retreat in early June, possible sooner. Thanks for the feedback!

**Comment by davidharting** [comment]
I am using this library in production and would also love to see denormalization. Currently using `reselect` to manually denormalize whenever necessary.

Also - amazing library! I evaluated a lot of options for normalizing JSON API payloads, and your library stood out above the rest!

**Comment by zeorin** [comment]
FYI in case no one has noticed: I've submitted a pull request that implements a denormalize function: #11.
cc @stevenpetryk

**Comment by stevenpetryk** [comment]
Hey there!

Upon looking more at the JSONAPI spec and @zeorin's PR (thanks for that 😊 ), this seems out of the scope of a JSONAPI client. 

See [this issue in JSONAPI](https://github.com/json-api/json-api/issues/205) for some help understanding my rationale.

The reason for this is that JSONAPI does not currently support embedding relationship objects into requests, so the concept of "denormalizing" does not really apply, since you can't _send_ `included` entities to the server with JSONAPI 1.0. You will be able to in 1.1, but there's not really a sign that much is going on in terms of getting that shipped.

I want this client to closely follow the spec but stay completely unopinionated in terms of out-of-spec behavior. I would recommend that if you need to marshal an entity from redux to JSONAPI's format, you should write that layer on a per-app basis.

Anybody have any thoughts? I would love to hear some ideas if I'm missing something! I will reopen if something compelling is shown.
